### ISSUE TITLE
Segfaults with profiling turned on

### ISSUE THREAD

**Issue by yongqli** [AccelerateHS/accelerate#260]
I have some code that segfaults sporadically when compiled with profiling turned on. As usual with these bugs, it's hard to produce a test case. Do you have any idea what's going on?

```
(gdb) bt
#0  0x00007fe94dfa7755 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#1  0x00007fe94dfb61f4 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007fe94df2bbef in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007fe94def16c2 in cuStreamDestroy_v2 () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#4  0x0000000003948a82 in ?? ()
#5  0x00007fe8d6289821 in ?? ()
#6  0x0000000000000000 in ?? ()
```

**Comment by yongqli** [comment]
`cuda-memcheck` says

    ========= Program hit CUDA_ERROR_CONTEXT_IS_DESTROYED (error 709) due to "context is destroyed" on CUDA API call to cuMemFree_v2.
    =========     Saved host backtrace up to driver entry point at error
    =========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 (cuMemFree_v2 + 0x145) [0x1365f5]

**Comment by yongqli** [comment]
I can only reproduce this when the code is run from `cabal test`. The exact same code doesn't cause any problems when put in its own program.

**Comment by robeverest** [comment]
The only time we call `cuStreamDestroy` is right before the program exits. Is this when you're getting the segfault?

**Comment by yongqli** [comment]
Yes.

**Comment by robeverest** [comment]
I think I may have found the problem. It's interesting that this only shows up with profiling and cabal test. I just pushed a potential fix to accelerate-cuda. Can you pull it and see if it works?

**Comment by yongqli** [comment]
The "context is destroyed" errors are gone, but the segfaults still happen. `cuda-memcheck` doesn't have much to say:

    ========= Error: process didn't terminate successfully
    =========        The application may have hit an error when dereferencing Unified Memory from the host. Please rerun the application under cuda-gdb or Nsight Eclipse Edition to catch host side errors.
    ========= Internal error (20)
    ========= No CUDA-MEMCHECK results found


The core dump is a bit different:


    (cuda-gdb) bt full
    #0  0x00007f4522d87755 in cuMemGetAttribute_v2 () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
    No symbol table info available.
    #1  0x00007f4522d961f4 in cuMemGetAttribute_v2 () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
    No symbol table info available.
    #2  0x00007f4522d0bbef in cuMemGetAttribute_v2 () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
    No symbol table info available.
    #3  0x00007f4522cd17ca in cuStreamDestroy_v2 () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
    No symbol table info available.
    #4  0x000000000394b022 in cudazu9zzLWWP0VEl23Gf5KnxFfrZZ_ForeignziCUDAziDriverziStream_finished_info ()
    No symbol table info available.
    #5  0x00007f44a5cc99b0 in ?? ()
    No symbol table info available.
    #6  0x0000000000000000 in ?? ()
    No symbol table info available.

**Comment by yongqli** [comment]
Actually, that's just because I ran it under `cuda-gdb` instead. The core dump is the same. It looks like the segfault is something else.

**Comment by robeverest** [comment]
Hmmm, I'm not sure what's causing this. Is it still occurring just before you would expect the program to exit?

**Comment by robeverest** [comment]
I think this is because we're not destroying resources in the right order, something that is hard to guarantee with finalizers. Hopefully what I've just pushed should fix the problem.

**Comment by yongqli** [comment]
Actually, after moving some stuff around, it doesn't seem to happen when the program is exiting after all.
The core dump is still the same:

    (cuda-gdb) bt full
    #0  0x00007ff79a1e3755 in cuMemGetAttribute_v2 () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
    No symbol table info available.
    #1  0x00007ff79a1f21f4 in cuMemGetAttribute_v2 () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
    No symbol table info available.
    #2  0x00007ff79a167bef in cuMemGetAttribute_v2 () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
    No symbol table info available.
    #3  0x00007ff79a12d7ca in cuStreamDestroy_v2 () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
    No symbol table info available.
    #4  0x00000000038612f2 in cudazu9zzLWWP0VEl23Gf5KnxFfrZZ_ForeignziCUDAziDriverziStream_finished_info ()
    No symbol table info available.
    #5  0x00007ff7215f5df1 in ?? ()
    No symbol table info available.
    #6  0x0000000000000000 in ?? ()
    No symbol table info available.

**Comment by yongqli** [comment]
Running under `cuda-gdb` I see some warnings:

    warning: Cuda API error detected: cuCtxPopCurrent_v2 returned (0xc9)

    warning: Cuda API error detected: cuCtxPopCurrent_v2 returned (0xc9)

**Comment by yongqli** [comment]
Now it segfaults even without profiling turned on. But it does not segfault when run under `cuda-gdb`.

**Comment by yongqli** [comment]
It looks like most accelerate programs generate the `cuCtxPopCurrent_v2 returned (0xc9)` warning.

**Comment by tmcdonell** [comment]
FYI: 0xc9 = 201 = Invalid context error

**Comment by tmcdonell** [comment]
I can successfully run profiling with the LLVM backends at least, so I think this is fixed now.
